"use client"

import * as React from "react"
import {
    Dialog,
    DialogContent,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { FileText, Printer, Building2, Phone } from "lucide-react"

export function ReferralModal() {
    return (
        <Dialog>
            <DialogTrigger asChild>
                <Button variant="secondary" className="w-full border-2 border-primary/20 hover:bg-primary/5" suppressHydrationWarning>
                    <FileText className="mr-2 h-4 w-4 text-primary" />
                    Jayadeva Referral
                </Button>
            </DialogTrigger>
            <DialogContent className="max-w-[800px] bg-white text-black p-0 overflow-hidden sm:rounded-xl">
                <div className="p-8 space-y-6">
                    {/* Header */}
                    <div className="flex justify-between items-start border-b-2 border-black pb-4">
                        <div className="space-y-1">
                            <DialogTitle className="text-2xl font-black uppercase tracking-tighter">Urgent Inter-Hospital Transfer</DialogTitle>
                            <p className="font-mono text-sm text-gray-600">Generated by CardioTriage AI • ID: REF-2025-8821</p>
                        </div>
                        <div className="text-right">
                            <div className="flex items-center justify-end gap-2 font-bold text-red-600 animate-pulse">
                                <SirenIcon className="h-5 w-5" />
                                PRIORITY: CRITICAL
                            </div>
                            <p className="text-xs font-mono">Time: {new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</p>
                        </div>
                    </div>

                    {/* Recipient */}
                    <div className="bg-gray-100 p-4 rounded border border-gray-300 flex items-start gap-4">
                        <Building2 className="h-6 w-6 text-gray-500 mt-1" />
                        <div>
                            <p className="text-xs font-bold uppercase text-gray-500">To</p>
                            <h2 className="text-lg font-bold">Jayadeva Institute of Cardiovascular Sciences</h2>
                            <p className="text-sm text-gray-700">Bannerghatta Main Rd, Phase 3, Jayanagar 9th Block, Bengaluru</p>
                            <p className="text-sm text-gray-700 font-mono mt-1">PCI Team On-Call (Ext: 4421)</p>
                        </div>
                    </div>

                    {/* Patient Info (Static Demo Data) */}
                    <div className="grid grid-cols-2 gap-8">
                        <div>
                            <p className="text-xs font-bold uppercase text-gray-500 mb-1">Patient</p>
                            <p className="font-mono text-lg font-bold">John Doe (58M)</p>
                            <p className="text-sm">Presenting: Acute Chest Pain (45m ago)</p>
                        </div>
                        <div>
                            <p className="text-xs font-bold uppercase text-gray-500 mb-1">Vitals (Last Recorded)</p>
                            <div className="grid grid-cols-3 gap-2 text-sm font-mono">
                                <div>HR: <b>130</b></div>
                                <div>BP: <b>190/110</b></div>
                                <div>SpO2: <b>57%</b></div>
                            </div>
                        </div>
                    </div>

                    {/* Clinical Findings */}
                    <div className="space-y-4">
                        <div>
                            <p className="text-xs font-bold uppercase text-gray-500 border-b border-gray-200 mb-2">ECG Analysis</p>
                            <p className="font-mono text-sm">
                                [CRITICAL] 3mm ST Elevation in leads V2-V5. Reciprocal depression in II, III, aVF.
                                <br />
                                <span className="text-red-600 font-bold uppercase">Diagnosis: Anterior Wall MI (STEMI)</span>
                            </p>
                        </div>
                        <div>
                            <p className="text-xs font-bold uppercase text-gray-500 border-b border-gray-200 mb-2">Administered Meds</p>
                            <ul className="list-disc list-inside text-sm font-mono">
                                <li>Aspirin 325mg (Chewable) @ 10:45 AM</li>
                                <li>Ticagrelor 180mg (Loading) @ 10:48 AM</li>
                                <li>Morphine 2mg IV @ 10:55 AM</li>
                            </ul>
                        </div>
                    </div>

                    {/* Footer Actions */}
                    <div className="bg-gray-50 p-4 border-t border-gray-200 flex justify-between items-center mt-8">
                        <div className="flex items-center gap-2 text-sm text-gray-500">
                            <Phone className="h-4 w-4" />
                            Referring Doctor: Dr. Koushik (DOC-8821)
                        </div>
                        <Button 
                            className="gap-2 bg-black hover:bg-gray-800 text-white"
                            onClick={() => window.print()} // ✅ Adds real print functionality
                        >
                            <Printer className="h-4 w-4" />
                            Print Transfer Packet
                        </Button>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    )
}

function SirenIcon(props: any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M7 12a5 5 0 0 1 5-5v0a5 5 0 0 1 5 5v6H7v-6Z" />
            <path d="M5 20a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v2H5v-2Z" />
            <path d="M21 12h1" />
            <path d="M18.5 4.5 18 5" />
            <path d="M2 12h1" />
            <path d="M12 2v1" />
            <path d="m4.929 4.929.707.707" />
            <path d="M12 7v5" />
        </svg>
    )
}