from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io
import datetime

def create_referral_pdf(patient_data):
    """
    Generates a PDF buffer for the patient referral.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # 1. Header (Red for Critical, Green for Stable)
    is_critical = "red" in str(patient_data.get("risk_level", "")).lower()
    
    c.setFillColor(colors.darkred if is_critical else colors.darkgreen)
    c.rect(0, height - 100, width, 100, fill=1, stroke=0)
    
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "EMERGENCY REFERRAL REPORT" if is_critical else "Medical Evaluation Report")
    
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 75, f"Generated by Triage AI • {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # 2. Patient Details
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 130, f"Case ID: {patient_data.get('case_id', 'Unknown')}")
    
    c.setFont("Helvetica", 12)
    y = height - 160
    vitals = patient_data.get('vitals', {})
    c.drawString(50, y, f"Heart Rate: {vitals.get('hr', 'N/A')} bpm")
    c.drawString(250, y, f"BP: {vitals.get('bp', 'N/A')} mmHg")
    c.drawString(450, y, f"SpO2: {vitals.get('spo2', 'N/A')}%")

    # 3. AI Analysis Section
    y -= 40
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "AI Risk Assessment")
    
    y -= 25
    c.setFont("Helvetica", 12)
    score = patient_data.get('risk_score', 0)
    c.drawString(50, y, f"Risk Score: {score}/10")
    
    y -= 20
    flags = patient_data.get('ai_analysis', {}).get('flags', [])
    if flags:
        c.drawString(50, y, "Clinical Flags Detected:")
        y -= 20
        c.setFillColor(colors.red)
        for flag in flags:
            c.drawString(70, y, f"• {flag}")
            y -= 20
    else:
        c.drawString(70, y, "No specific clinical flags detected.")

    # 4. Footer
    c.setFillColor(colors.gray)
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "This document was generated by AI assistant. Please verify clinically.")

    c.save()
    buffer.seek(0)
    return buffer